#!/usr/bin/env php

<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

$application = new Application();
$application->setName("Aegis Backup");
$application->setVersion("2.0 (codename Nox Aeternum)");

$application->add(new \Aegis\Commands\LocalBackup());
$application->add(new \Aegis\Commands\DropboxBackup());
$application->add(new \Aegis\Commands\NextCloudBackup());

$application->run();